### ISSUE TITLE
Border for a tooltip

### ISSUE THREAD

**Issue by ritesh94** [tomergoldst/tooltips#25]
@tomergoldst 
is there any way of adding border/stroke using width and color?

**Comment by tomergoldst** [comment]
A border or stroke are part of a background drawable and at the moment in this library the background drawables are fixed. Thus the answer to your question is no.

**Comment by SuryaDotNet** [comment]
@tomergoldst how to set the custom width of tooltip popup? I tried so many ways but can't, is there any way to it?
