### ISSUE TITLE
Make function to move ToolTip afterwards public

### ISSUE THREAD

**Issue by Nop0x** [tomergoldst/tooltips#26]
Heya!

Im currently dealing with changing the text of a tooltip after creating it. With a new text its positioning above the view is incorrect.

I see you have a function for moving the tip, is it possible to make that function publich so someone can manually reposition the tooltip aligning with the view?

Thanks!

Marvin / Nop0x

**Comment by tomergoldst** [comment]
Hey,

The method of moving the tooltip into correct position after content change is subject to recalculate the updated tooltip size and basicly is equivalent to adding a new tooltip.
Have you tried to just remove the existing tooltip and add a new one with the updated content?
If you did tried that and still want an option to update the tooltip content, can you explain in more details how it will help you?

**Comment by tomergoldst** [comment]
As I can understand from your example it seems that using the ToolTips library for your case is not the best choice.  You are trying to achive a badge effect more then a tooltip effect. I would recommend you to create the `currentJoin` view and `maxJoin` view as part of your layout with a drawable as background and then you'll won't have any issue to update the text cause the layout constraints will make sure it will always be centered.

Regarding your sidenote, A quick check reveal that the coordinator finder return wrong values when trying to find the location of the `popupWindow` thus placing the tooltip at a wrong position out of visible area.
