### ISSUE TITLE
Tooltip view going outside of parent view.

### ISSUE THREAD

**Issue by kashifo** [tomergoldst/tooltips#27]
Hi,
I'm facing this issue, the tooltip view is going outside of the parent view (check screenshot attached).

I'm using RelativeLayout as parent and ImageView as target.

```java

ToolTipsManager mToolTipsManager = new ToolTipsManager( toolTipDismiss );
ToolTip.Builder builder = new ToolTip.Builder(Detail_Page_Looks.this,
                        view, relSet, pojo.getPrdt_name(), tooltipPos)
                        .setBackgroundColor(getResources().getColor(R.color.black));

mToolTipsManager.dismissAll();
mToolTipsManager.show(builder.build());

```

Screenshot:
![tooltip_issue](https://user-images.githubusercontent.com/13944934/49873276-7ab7df00-fe41-11e8-8025-bcc4e373abb8.jpg)

**Comment by kashifo** [comment]
Hi,
I didn't used any offset value for tooltip, regarding tooltip I've used only the code i typed in above comment.

I've used offset for imageview whose position is dynamic, the imageview is inside relativelayout, the imageview is not static, it's added at runtime. it's top left position is inside visible window.

**Comment by tomergoldst** [comment]
It's difficult to understand the issue without the code and xml
Can you go into detail about offset for imageview and post your xml and relevant code?

**Comment by kashifo** [comment]
Hi @tomergoldst 
The XML has only RelativeLayout, the ImageView which is white color tag image is added to the RelativeLayout dynamically.

For my scenario this other tooltip [library](https://github.com/florent37/ViewTooltip) worked, You may close it

**Comment by tomergoldst** [comment]
Ok
