### ISSUE TITLE
RecyclerView

### ISSUE THREAD

**Issue by johnvazna** [tomergoldst/tooltips#28]
¿This work inside Recyclerview?

**Comment by larkonesvk** [comment]
It does not work for recyclerview in my case neither.

**Comment by asadmukhtar28** [comment]
What kind of scenario you want to cover using ToolTip in Recyclerview, recently in a project i use tooltip on a horizontal recyclerview, i created the tooltip at a 0th item of the recyclerview, i`m facing the problem that is it is just stuck at a screen while the recyclerview scrolls. Have you faced this kind of issue? @Jonathanvazna

**Comment by LinDevHard** [comment]
works fine, the main thing is to specify the root ViewGroup correctly
