### ISSUE TITLE
  Tooltip goes out of the screen.

### ISSUE THREAD

**Issue by asadmukhtar28** [tomergoldst/tooltips#31]
Check this tooltip goes out of the screen.

![e9a0712f-a735-40c6-9375-cfd81750d83b](https://user-images.githubusercontent.com/22379988/64094561-9cf9e000-cd75-11e9-9b74-9e2e7e7d1675.jpg)

**Comment by Zennaxxtech** [comment]
If you can set `builder.setPosition(ToolTip.POSITION_BELOW);` then your ToolTips window will be show's below your specified view. I this is not your prefect solution but you can fix by this way.
