### ISSUE TITLE
ToolTip showing but not visible to the screen.

### ISSUE THREAD

**Issue by asadmukhtar28** [tomergoldst/tooltips#32]
I have a requirement to show tooltip on few buttons and in the middle of screen i have recyclerview, i created tooltip and the anchor view is buttons, but after getting results from server tooltip shown on back side of recyclerview like it is showing but recyclerview over lap it so is there any option of showing tooltip all over the other views.

**Comment by tomergoldst** [comment]
You can try to set bigger elevation for the tooltip
