### ISSUE TITLE
Hide ToolTip On Click of Other View

### ISSUE THREAD

**Issue by hafilpallippadi** [tomergoldst/tooltips#34]
How do I hide the tooltip on other view Click?

**Comment by tomergoldst** [comment]
public class MainActivity extends Activity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        
        mDismissBtn.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                mToolTipsManager.findAndDismiss(mTextView);
            }
        });
    }
}

Where mTextView is the anchor view of the tooltip
