### ISSUE TITLE
JCenter sunset is announced; please republish library version(s) to Maven Central 

### ISSUE THREAD

**Issue by dejan2609** [tomergoldst/tooltips#35]
**_Rationale_**: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Quote (from a link above):
> **_May 1st | Bintray, JCenter, GoCenter, and ChartCenter services will no longer be available_**

**_Note:_** it seems that Signal Android app depends on this (among many other projects).

@tomergoldst  Let me know if I can help you with this.

**Comment by tomergoldst** [comment]
Library published to Maven Central
