### ISSUE TITLE
Tooltip box size 

### ISSUE THREAD

**Issue by jameper** [tomergoldst/tooltips#36]
There is an issue with the tooptip popup being way to large for the contents. Works for other items, but seems to re-size incorrectly on these datepickers.

Is there a way to override the X/Y of these popup boxes to fix this issue?

![ToolTipBug](https://user-images.githubusercontent.com/27213931/108226439-d3c3e180-7134-11eb-876b-6585cfb74729.gif)

**Comment by tomergoldst** [comment]
Tooltip measure itself before drawing and should take as little space as possible.
You should check the value of your strings, Maybe you have spaces. Try to use `trim() `
If this isn't the issue please provide a sinppet code

**Comment by jameper** [comment]
The value for the string is "a", seems as though my issue is similar to issues previously raised: https://github.com/tomergoldst/tooltips/issues/29
Any ideas what was causing that one?

**Comment by tomergoldst** [comment]
What viewgroup type is your root layout?

**Comment by jameper** [comment]
We're using a ContentView, and the page is split up using a grid column&row definitions. We've also tried wrapping the controls on the page within Frames, without and success

**Comment by tomergoldst** [comment]
Can you post your layout xml and the lines of code where you create the tooltip?
