### ISSUE TITLE
How to add Translation animation?

### ISSUE THREAD

**Issue by zaaach** [tomergoldst/tooltips#38]
like this
[https://github.com/sephiroth74/android-target-tooltip/raw/master/screenshots/video2.gif](https://github.com/sephiroth74/android-target-tooltip/raw/master/screenshots/video2.gif)

**Comment by tomergoldst** [comment]
There isn't any build in way but when you call to show your tooltip you get back the view, You can then manipulate this view properties
```View view = mToolTipsManager.show(builder.build());```

**Comment by zaaach** [comment]
Thanks! I will try it.
