### ISSUE TITLE
Tooltip size depending on text length

### ISSUE THREAD

**Issue by jan-sochor** [tomergoldst/tooltips#39]
Hey,
when I use your tooltip with short text, don't know really the precise length, the tooltip is shown through the whole screen.

![Screenshot 2021-09-20 at 13 18 54](https://user-images.githubusercontent.com/71444276/133994442-224dd23b-e742-473f-840b-32e826ed892c.png)

When I used your tooltip with longer text it is displayed correctly.

![Screenshot 2021-09-20 at 13 18 13](https://user-images.githubusercontent.com/71444276/133994676-9e772cf8-7d69-4546-b221-95e18a38beac.png)

String is trimmed. 

The problem with short text can be resolved by adding Padding to this string, but the final tooltip box has the width from start to the edge of screen which doesn't look quite nice. 

Tooltip position bellow
Align.Left
Gravity.Left

Maybe its just me and I forget to set something to the builder.

**Comment by aneta9** [comment]
Yes, same issue. I love this tooltip  but I realized that I can't control the width of the tool tip box and the text flows to the next line only when it takes the full width of the screen. Would be great to be able to control the width in one way or another or at least have it respond to \n (nextline).

**Comment by tomergoldst** [comment]
You can now control the max width of a tooltip with version 1.1.1

```
toolTip.setMaxWidth(200)
```

**Comment by aneta9** [comment]
waw, thank you for the info! will try that!
