### ISSUE TITLE
 builder.setTextSize(11); is not avaliable in 1.0.10

### ISSUE THREAD

**Issue by Kiru3014** [tomergoldst/tooltips#41]
Hi i have update to 1.0.10 in that         builder.setTextSize(11);
 is not available hot test text size in 1.0.10

**Comment by Kiru3014** [comment]
i don't want to down grad because in 1.0.10 we have customer font face so help me to know how to set text in 1.0.10

**Comment by tomergoldst** [comment]
You should define a text style and use it
```xml
  <style name="TooltipTextAppearance">
        <item name="android:textColor">@android:color/white</item>
        <item name="android:textSize">16sp</item>
    </style>
```
```java
builder.setTextAppearance(R.style.TooltipTextAppearance);
```
see styles.xml in the demo app
