### ISSUE TITLE
Allow HTML or Spanned text

### ISSUE THREAD

**Issue by donjerick** [tomergoldst/tooltips#8]
Hi, would like to request a feature that allows the Tooltip.Builder to accept Spanned text for the message parameter. Also allowing links on the tooltip. Thank you for this useful library!

**Comment by donjerick** [comment]
Also if you can consider the following:
- Allow change on corner radius.
- Add shadow (not sure if this is included in setElevation(); )
- Allow change on text size, typeface.

Thank you!

**Comment by tomergoldst** [comment]
Hi, 
I will check the possibilty to add a more customized text like you requested. 

About your request of a link at the tooltip, Do you know that you can use the onTipDismissed interface to react when a tip is being dismissed? and thus do anything on your mind like open a web view.  
If you want to dismiss a tip as response to user interaction you can call 'findAndDismiss'  from code. A good way to react to any user action on screen is to override 'onUserInteraction' of an activity.

This library uses 9-patch images for the tip background thus corner radius and shadow are fixed, The setElevation here has been modfied to discard the dynamic shadow cause it can't work well in this case but it's still important in cases where you might have a view with higher elevetion hiding your tip. I do have intention to replace those with vector shapes in the future.

Have a nice day!

**Comment by tomergoldst** [comment]
Hi @donjerick 

Version 1.0.3 with spannable text support was releasesd. Just use the constructor with spannable parameter instead of the normal constructor.
