### ISSUE TITLE
Tooltip is not moving in Scrollview!

### ISSUE THREAD

**Issue by khaledkhj** [tomergoldst/tooltips#9]
Thank you for this great library, but there is an issue here in using ScrollView or NestedScrollView!
Tooltip keeps it location as it was shown the first time, and not moving if we scroll up or down!

**Comment by tomergoldst** [comment]
The tooltip is added to the layout you provided when you constructed the tip. If you specified a layout that is not part of the scrollView then it will remain at a fixed position. If you which the tooltip to move when scrolling you have to add it to a layout under the scrollView
